export const providers = [
  {
    id: 1,
    name: 'OpenAI Platform v2',
    desc: 'OpenAI API Authentication Provider',
    method: 'GET',
    validUrl: 'https://api.openai.com/v1/models',
    config: {
      location: 'headers',
      key: 'Authorization',
      prefix: 'Bearer ',
      tokenFormat: 'apiKey',
    },
    strategy: 'STATIC',
    shared: true, // global
    enabled: true,
    tenantPk_: 0,
    createdBy: 'system',
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
    deletedAt: 0,
  },
  {
    id: 2,
    name: 'Internal LDAP System (Legacy)',
    desc: 'Internal LDAP authentication for legacy systems',
    method: 'POST',
    validUrl: 'https://ldap.internal.com/auth',
    config: {
      location: 'headers',
      key: 'X-API-Key',
      tokenFormat: 'basic',
    },
    strategy: 'DYNAMIC',
    shared: null, // tenant
    enabled: true,
    tenantPk_: 0,
    createdBy: 'admin',
    createdAt: '2024-02-15T00:00:00.000Z',
    updatedAt: '2024-02-15T00:00:00.000Z',
    deletedAt: 0,
  },
  {
    id: 3,
    name: 'AWS Signature v4',
    desc: 'AWS SigV4 authentication provider',
    method: 'GET',
    validUrl: 'https://sts.amazonaws.com/',
    config: {
      location: 'headers',
      key: 'Authorization',
      tokenFormat: 'jwt',
      algorithm: 'AWS4-HMAC-SHA256',
      algorithmParams: {
        region: 'us-east-1',
        service: 'sts',
      },
      uidExpl: '$.GetCallerIdentityResponse.GetCallerIdentityResult.Arn',
    },
    strategy: 'REFRESHABLE',
    shared: false, // self
    enabled: true,
    tenantPk_: 0,
    createdBy: 'admin',
    createdAt: '2024-03-01T00:00:00.000Z',
    updatedAt: '2024-03-01T00:00:00.000Z',
    deletedAt: 0,
  },
];

export const realms = [
  {
    pk: 2001,
    id: 'openai-auth',
    name: 'OpenAI Authentication Realm',
    desc: 'Realm for OpenAI API key verification only',
    enabled: true,
    shared: true, // tenant
    providerId: 1,
    principalPk: 1001,
    pricing: null,
    tenantPk_: 0,
    createdBy: 'system',
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-11-25T00:00:00.000Z',
    deletedAt: 0,
  },
  {
    pk: 2002,
    id: 'internal-admin-sso',
    name: 'Internal Admin SSO',
    desc: 'Single Sign-On for internal dashboard access',
    enabled: true,
    shared: false, // self
    providerId: 2,
    principalPk: 1002,
    pricing: null,
    tenantPk_: 0,
    createdBy: 'admin',
    createdAt: '2024-02-20T00:00:00.000Z',
    updatedAt: '2024-11-28T00:00:00.000Z',
    deletedAt: 0,
  },
];
