export const providers = [
  {
    id: 1,
    name: 'OpenAI Platform v2',
    desc: 'OpenAI API Authentication Provider',
    method: 'GET',
    validUrl: 'https://api.openai.com/v1/models',
    attachType: 'BEARER',
    config: {
      location: 'headers',
      key: 'Authorization',
      prefix: 'Bearer ',
      tokenFormat: 'apiKey',
    },
    shared: 'global',
    enabled: true,
    tenantPk_: 0,
    createdBy: 'system',
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
    deletedAt: 0,
  },
  {
    id: 2,
    name: 'Internal LDAP System (Legacy)',
    desc: 'Internal LDAP authentication for legacy systems',
    method: 'POST',
    validUrl: 'https://ldap.internal.com/auth',
    attachType: 'BASIC',
    config: {
      location: 'headers',
      key: 'X-API-Key',
      tokenFormat: 'basic',
    },
    shared: 'tenant',
    enabled: true,
    tenantPk_: 0,
    createdBy: 'admin',
    createdAt: '2024-02-15T00:00:00.000Z',
    updatedAt: '2024-02-15T00:00:00.000Z',
    deletedAt: 0,
  },
];

export const realms = [
  {
    pk: 2001,
    id: 'openai-auth',
    name: 'OpenAI Authentication Realm',
    desc: 'Realm for OpenAI API key verification only',
    enabled: true,
    shared: 'global',
    providerId: 1,
    principalPk: 1001,
    pricing: null,
    tenantPk_: 0,
    createdBy: 'system',
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-11-25T00:00:00.000Z',
    deletedAt: 0,
  },
  {
    pk: 2002,
    id: 'internal-admin-sso',
    name: 'Internal Admin SSO',
    desc: 'Single Sign-On for internal dashboard access',
    enabled: true,
    shared: 'private',
    providerId: 2,
    principalPk: 1002,
    pricing: null,
    tenantPk_: 0,
    createdBy: 'admin',
    createdAt: '2024-02-20T00:00:00.000Z',
    updatedAt: '2024-11-28T00:00:00.000Z',
    deletedAt: 0,
  },
];